name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - stage
          - prod
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'release'
        type: string
      release_notes:
        description: 'Release notes'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}  # Use the branch passed from the input

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying branch ${{ github.event.inputs.branch }} to ${{ github.event.inputs.environment }}"
          echo "Release notes: ${{ github.event.inputs.release_notes }}"
          # Add your deployment commands here (e.g., kubectl, terraform, etc.)

      - name: Store Release Notes
        run: |
          echo "${{ github.event.inputs.release_notes }}" > release-notes.txt
          # Optionally store or process the release notes
